spring:
  application:
    name: cart-service
  server:
    port: 8081
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/carts_service?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: admin
    password: admin
