spring:
  application:
    name: products-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/products_service?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: admin
    password: admin
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
